# Generated by Django 5.0 on 2023-12-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bolo_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bolo',
            options={'verbose_name': 'Bolo', 'verbose_name_plural': 'Bolos'},
        ),
    ]
