# Generated by Django 5.0 on 2023-12-18 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_bolo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bolo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
