# Generated by Django 5.0 on 2023-12-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_bolo_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolo',
            name='foto',
            field=models.ImageField(null=True, upload_to='bolos'),
        ),
    ]
